name: Commit-Tests

on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: >
        ./tests/test1.ps1
        
